book/src/02_basic_calculator/10_as_casting.md

```
% python3
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 0b0_0_0_0_0_0_1_0_0_0_0_0_0_0_0_0
512
>>> 0b0_0_0_0_0_0_0_1_0_0_0_0_0_0_0_0
256
```
:)

10_as_casting.md: fix 256 bit representation

---

book/src/04_traits/10_clone.md

The clone() illustration shows two `s` values in the stack when one of them is the original `s` value which got cloned and the other one should be the new `t` value created from `s`.
Rename the second value from `s` to `t`.

Fix typo in 10_clone.md illustration

---

book/src/02_basic_calculator/06_while.md

Thank you for the great resource! As I was walking through, I noticed a small clarification issue regarding the `while` section in the book:
https://rust-exercises.com/02_basic_calculator/06_while
For the following code snippet
```rust
let sum = 0;
let i = 1;
// "while i is less than or equal to 5"
while i <= 5 {
// `+=` is a shorthand for `sum = sum + i`
sum += i;
i += 1;
}
```
`This will keep adding 1 to sum until i is no longer less than or equal to 5.`
This isn't true. What's correct is
`This will keep adding 1 to i and i to sum until i is no longer less than or equal to 5.`
For what it's worth, the program isn't meant to compile as it comes right before introducing `mut`, I just thought that it's nice to be descriptively correct for clarity.

fix spelling error

---

exercises/05_ticket_v2/09_error_trait/src/lib.rs

The commented instructions of the exercise ask to use `No description provided` for the description field when calling `easy_ticket` with an invalid description argument. However, the unit test of that behavior compares the description to `Description not provided` instead.
Previous exercises in that part also use `Description not provided`.
Update the exercise 05_ticket_v2/09_error_trait instructions to use `Description not provided` as an expected default  description value when calling `easy_ticket` with no description instead of `No description provided`.

Fix typo in 05_ticket_v2/09_error_trait/[...] instructions

---

book/src/04_traits/08_from.md
exercises/04_traits/08_from/src/lib.rs

misusing the verb `implements`.
impl for T means T implement something (maybe a trait).
```rust
impl<T, U> Into<U> for T
where
U: From<T>,
```
the  trait bounds `U: From<T>` mean U implements From<T> trait.

misunderstand the implements verb

---

book/src/03_ticket_v1/08_stack.md

The type argument of `size_of` is `<u8>` instead of `<String>`.

Fix a typo in 03_ticket_v1/08_stack

---

exercises/07_threads/10_patch/tests/check.rs

We want to check whether the ticket's `status` field was actually patched to `Status::InProgress`.

07_threads/10_patch: Check status field value after patch

---

exercises/04_traits/01_trait/src/lib.rs

Without an explicit suffix, the compiler is able to use the i32
implementation without the need for an u32 implementation.

Add i32/u32 suffix for numeric literals in 04_traits/01_trait

---

book/src/02_basic_calculator/08_overflow.md

Did a quick check using a small regex `\[\^.+\]` and didn't find any others so I think is the only one.

Remove unused footnote

---

book/src/04_traits/03_operator_overloading.md

While I do not think it is confusing as is, I think technically syntax is being used as an adjective because sugar is the noun in the sentence so the adjective version of syntax is syntactic and that's why I am proposing changing it.

Change part of speech for syntax

---

book/src/04_traits/05_trait_bounds.md
book/src/04_traits/06_str_slice.md
book/src/04_traits/07_deref.md
book/src/04_traits/08_sized.md
book/src/04_traits/09_from.md
book/src/04_traits/10_assoc_vs_generic.md
book/src/04_traits/11_clone.md
book/src/04_traits/12_copy.md
book/src/04_traits/13_drop.md
book/src/04_traits/14_outro.md

- Add 'References' section in `book/src/04_traits/05_trait_bounds.md` for consistency
- Update paths for exercises
Related: https://github.com/mainmatter/100-exercises-to-learn-rust/commit/453d8030e5b4c6a43cf91b2f075b28f6c2d37ec2

Update references in `book/src/04_traits`

---

book/src/05_ticket_v2/09_error_trait.md

The name of the variant used in the previous exercise is `TitleError`, not `InvalidTitle` (https://github.com/mainmatter/100-exercises-to-learn-rust/blob/solutions/exercises/05_ticket_v2/08_error_enums/src/lib.rs#L20)

Update variant name

---

book/src/08_futures/02_spawn.md

I'm not very sure of this one but based on my understanding it would propagate the panic to the current task which would again be caught by the executor

Change execution unit name

---

book/src/03_ticket_v1/06_ownership.md

I think the ownership transfer bits can use a better example.
The value 42 is just copied into the new variable, so this example does demonstrate the functioning of the borrow checker.
let a = 42;
let b = a;
println!("a is {}, b is {}", a, b);
Outputs
a is 42, b is 42
But on changing to a `String` value
let a = String::from("hello");
let b = a;
println!("a is {}, b is {}", a, b);
We get a better demonstration
```
Compiling my-project v0.1.0 (/Users/keshav/my-project)
error[E0382]: borrow of moved value: `a`
--> src/main.rs:8:34
|
6 |     let a = String::from("hello");
|         - move occurs because `a` has type `String`, which does not implement the `Copy` trait
7 |     let b = a;
|             - value moved here
8 |     println!("a is {}, b is {}", a, b);
| …
```

Better example for ownership transfer using String

---

book/src/04_traits/05_trait_bounds.md

The book previously recommended using camel case for type parameter names

fix(book): Correct type parameter naming convention to pascal case

---

exercises/03_ticket_v1/04_visibility/src/lib.rs

The output of the compiler does not include the module name of the `Ticket` struct and the root module of this exercise is `visibility` rather than `encapsulation` which is the root module of the next exercise.

fix(typo): remove a module name in comments

---

book/src/07_threads/03_leak.md

07_threads: 03_leak: Leak vector with Vec::leak, not Box::leak

---

exercises/07_threads/08_client/src/lib.rs

The argument has a private type. This gets rid of the `private_interfaces` warning.

Remove pub visibility on `server()`

---

book/src/07_threads/09_bounded.md

Trim errant `s` from `enqueue`'s end in [Bounded vs unbounded channels](https://rust-exercises.com/100-exercises/07_threads/09_bounded.html):
`if the producers enqueues messages` -> `if the producers enqueue messages`

Fix minor typo in 09_bounded.md

---

book/src/05_ticket_v2/09_error_trait.md

The [Error trait](https://rust-exercises.com/100-exercises/05_ticket_v2/09_error_trait.html?highlight=supertrait#the-error-trait) chapter states that the reader may recall the supertrait syntax from the [Sized trait](https://rust-exercises.com/100-exercises/04_traits/08_sized) chapter. Actually the syntax is introduced in the [From and Into](https://rust-exercises.com/100-exercises/04_traits/09_from) chapter instead. This PR amends the text accordingly.

Fix reference to supertrait syntax in 09_error_trait.md

---

exercises/05_ticket_v2/09_error_trait/src/lib.rs

Following up on #139, for removing extra `.clone()` calls.

Fix remove redundant clone

---

book/src/06_ticket_management/00_intro.md

Slices are already mentioned in bullet point 4, so they can be removed from bullet point 2.

Remove duplicated mention of slices in 00_intro.md

---

book/book.toml

Without this attribute, all lines starting with `#` are stripped away when going through `mdbook-pandoc`. In particular, all macros, as you can see in the code snippets for section 4.4 on derive macros.

Don't omit macros from PDF and ePUB versions

---

.github/workflows/ci.yml
book/book.toml
book/custom.theme

Style book

---

exercises/08_futures/03_runtime/src/lib.rs

The binding is never used, we avoid a warning.

Update lib.rs binding in the solution

---

exercises/05_ticket_v2/15_outro/src/title.rs

Characters was meant to be bytes, this was missed in a former refactoring

05_ticket_v2 outro: correct comment on title

---

.github/workflows/ci.yml

- Adds a workflow_dispatch trigger so the CI can be manually triggered
- Adds a schedule trigger to run at the beginning of each month.
Github actions artifacts expire after 90 days. So we'll periodically refresh them.
For use in https://github.com/mainmatter/rust-exercises.com
Same as https://github.com/mainmatter/rust-python-interoperability/pull/9 and https://github.com/mainmatter/rust-advanced-testing-workshop/pull/6

chore(ci): re-create book artifacts at the beginning of each month

---

.github/workflows/ci.yml
book/book.toml

Those action runs don't have access to our private font repo so we're using a fallback font instead.

Fix builds for PRs originating from forks

---

exercises/02_basic_calculator/10_as_casting/src/lib.rs

Fix docstring: "when converted to `u8`"

---

exercises/07_threads/09_bounded/src/lib.rs

`fn server()` does not need to be public (and will raise a warning if it is), similarly to how it already is in exercise `08_client`.

Update lib.rs: made fn server non-public

---

exercises/06_ticket_management/04_iterators/src/lib.rs
exercises/06_ticket_management/05_iter/src/lib.rs

Give a more structured hint for iteration exercises

---

book/src/07_threads/14_sync.md

Clarify Send-Sync relationship

---

book/link2alias.json
book/src/03_ticket_v1/09_heap.md
site/_redirects

Was going through the course and found that this link no longer works, so I replaced it with the latest web archive of the original URL.

Fix dead link to blog.acolyer.org

---

book/src/02_basic_calculator/08_overflow.md

I have noticed a few small issues in the **Profiles** section, so I propose these changes:
* Fix a typo - change "form" to "from". 
* Remove "etc.", as it should not be used together with "e.g.".

Fix typos in 08_overflow.md.
